 &files wffile='restart'/
 &force name='Sly5', pairing='NONE' /
 &main mprint=10,mplot=0,
  mrest=500000,writeselect='rc',
  imode=2,tfft=T,nof=1 /
 &grid nx=24,ny=24,nz=24,dx=0.8,dy=0.8,dz=0.8,
	periodic=F /
 &dynamic nt=50000, dt=0.2, mxpact=4, texternal=T/
 &extern ipulse=0,isoext=0,ampl_ext=5D-5,L_val=0,M_val=0,radext=200D0,widext=1D0,
         textfield_periodic=F /
 &fragments filename=1*'../Static/Pb208',fix_boost=T,
      fcent(1,1)=0,0,0    /
